version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: product
    ports:
      - "5432:5432"

  product-etl:
    build: ./product-etl
    container_name: product-etl
    depends_on:
      - elasticsearch

  product-api:
    build: ./product-api
    container_name: product-api
    depends_on:
      - elasticsearch
      - redis
      - product-etl

  product-config-api:
    build: ./product-config-api
    container_name: product-resource-api
    depends_on:
      - redis
