server:
  port: 3000
elasticsearch:
  host: "http://elasticsearch"
  port: 9200
  index: "product-index"
productConfigClient:
  url: "http://product-resource-api:3001"
redis:
  host: "redis"
  port: 6379
  eventName: "productConfigCacheInvalidate"
